### ISSUE TITLE
文末などの文節機能部について

### ISSUE THREAD

**Issue by seiichiinoue** [jqk09a/style-sensitive-word-vectors#1]
論文中で言及されていた，前処理段階での，スタイルを学習しやすくするための “わ + よ + ね” のよ うな文末表現の連結はどのように実装されましたか？
一応，参照論文も拝見したのですが，本プロジェクトと参照論文でのプロジェクトで使用されているデータセットが違ったため，実装の参考にはなりませんでした...

**Comment by jqk09a** [comment]
具体的な手順としては，形態素解析の後，機能語にあたる単語を文末から見て最長でひとまとまりにして，これを "文末" として扱います．たとえば「行くに決まってるわよね」という文では，以下のように文末の3つの助詞（機能語）を連結することにより「わよね/文末」を得ます:
行く/動詞 に/助詞 決まっ/動詞 てる/動詞 **わ/助詞+よ/助詞+ね/助詞** -> **わよね/文末**

論文内3.1節で言及しているように，日本語データセットにおける我々の文末表現は以下の研究の "sentence-end expressions" （2ページ目, 3章）を参考にしています: https://www.aclweb.org/anthology/Y15-1035/ .

**Comment by seiichiinoue** [comment]
お返事ありがとうございます．赤間さんの研究を参考にさせていただいていたのですが，再現実装で詰まったので質問させていただきました．
具体的な回答ありがとうございます．引用いただいた論文について，私の方では日本語の論文を参照していたのですが，そちらにもよく読んだら品詞情報を使用して書き換え規則集を作成すると書いてありました．それに従って実装してみたいと思います！
